apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-hook-example
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/abhi0498/argo-example" # Replace with your repo URL
    targetRevision: HEAD
    path: "."
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
