apiVersion: apps/v1
kind: Deployment
metadata:
  name: pre-sync-hook
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pre-sync-hook
  template:
    metadata:
      labels:
        app: pre-sync-hook
    spec:
      serviceAccountName: sync-hook-sa
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -ex
              CURRENT_TIME=$(date '+%Y-%m-%d %H:%M:%S')
              echo "Starting PreSync hook at $CURRENT_TIME"
              kubectl patch configmap last-sync-time -n default --type=merge -p "{\"data\":{\"lastSync\":\"$CURRENT_TIME\"}}"
              echo "Verifying update..."
              kubectl get configmap last-sync-time -n default -o yaml
