apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-hook-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: sync-hook-sa
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Starting hook..."
              echo "Current ConfigMap state:"
              kubectl get configmap last-sync-time -n default -o yaml || true

              echo "\nAttempting to patch..."
              kubectl patch configmap last-sync-time -n default --type=merge -p "{\"data\":{\"lastSync\":\"$(date)\"}}"

              echo "\nFinal ConfigMap state:"
              kubectl get configmap last-sync-time -n default -o yaml

              echo "\nHook completed"
      restartPolicy: Never
