apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-hook-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              kubectl create configmap sync-status --from-literal=lastSync="$(date)" -n default --dry-run=client -o yaml | kubectl apply -f -
      restartPolicy: Never
