apiVersion: apps/v1
kind: Deployment
metadata:
  name: pre-sync-hook
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pre-sync-hook
  template:
    metadata:
      labels:
        app: pre-sync-hook
    spec:
      serviceAccountName: sync-hook-sa
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "Starting PreSync hook..."
              echo "Attempting to patch ConfigMap..."
              kubectl patch configmap last-sync-time -n default --type merge -p "{\"data\":{\"lastSync\":\"$(date)\"}}"
              echo "ConfigMap patched successfully"
