apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-hook-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: sync-hook-sa
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -ex
              CURRENT_TIME=$(date '+%Y-%m-%d %H:%M:%S')
              echo "Starting PostSync hook at $CURRENT_TIME"

              # Update only the lastSync field
              kubectl patch configmap last-sync-time -n default --type=strategic --patch "
              data:
                lastSync: \"$CURRENT_TIME\"
              "

              # Verify
              echo "Updated ConfigMap:"
              kubectl get configmap last-sync-time -n default -o yaml
      restartPolicy: Never
